<%
require 'yaml'
dse_creds = YAML.load_file('dse_creds.yaml')
%>
---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 50

platforms:
  - name: bento/centos-7.1

verifier:
  name: inspec
  format: documentation

provisioner:
  name: chef_solo
  require_chef_omnibus: '13.2.20'

suites:
  - name: studio
    run_list:
      - recipe[java]
      - recipe[dse_studio::studio]
    attributes:
      java:
        install_flavor: 'openjdk'
        jdk_version: 8
      dse:
        studio:
          repo_user: <%= dse_creds['repo_user'] %>
          repo_pass: <%= dse_creds['repo_pass'] %>
